# Generated by Django 5.2.5 on 2025-09-27 20:14

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator('\\w+\\.\\w+', message='Topic must match: \\w+\\.\\w+')])),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('SUCCESS', 'SUCCESS')], default='PENDING', editable=False, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(editable=False)),
                ('topic', models.CharField(editable=False, max_length=250, null=True)),
                ('webhook', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='organisations.organizationwebhook')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(12)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', related_query_name='secret', to='organisations.organizationwebhook')),
            ],
        ),
    ]
